In [1]:
import pandas as pd
import json
from sqlalchemy import create_engine

In [2]:
pokedex_df = pd.read_json("complete_pokedex_data.json", orient='records')

In [3]:
pokedex_df.head(10)

,num,name,types,genderRatio,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,...,tags,baseForme,cosmeticFormes,maxHP,requiredAbility,battleOnly,requiredMove,requiredItems,cannotDynamax,forceTeraType
0,1,Bulbasaur,"[Grass, Poison]","{'M': 0.875, 'F': 0.125}",45,49,49,65,65,45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ivysaur,"[Grass, Poison]","{'M': 0.875, 'F': 0.125}",60,62,63,80,80,60,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,"[Grass, Poison]","{'M': 0.875, 'F': 0.125}",80,82,83,100,100,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Venusaur-Mega,"[Grass, Poison]","{'M': 0.875, 'F': 0.125}",80,100,123,122,120,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,Venusaur-Gmax,"[Grass, Poison]","{'M': 0.875, 'F': 0.125}",80,82,83,100,100,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,4,Charmander,[Fire],"{'M': 0.875, 'F': 0.125}",39,52,43,60,50,65,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,5,Charmeleon,[Fire],"{'M': 0.875, 'F': 0.125}",58,64,58,80,65,80,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6,Charizard,"[Fire, Flying]","{'M': 0.875, 'F': 0.125}",78,84,78,109,85,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,6,Charizard-Mega-X,"[Fire, Dragon]","{'M': 0.875, 'F': 0.125}",78,130,111,130,85,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,6,Charizard-Mega-Y,"[Fire, Flying]","{'M': 0.875, 'F': 0.125}",78,104,78,159,115,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
pokedex_df.columns

Index(['num', 'name', 'types', 'genderRatio', 'HP', 'Attack', 'Defense',
       'Sp.Atk', 'Sp.Def', 'Speed', 'abilities', 'heightm', 'weightkg',
       'color', 'evos', 'eggGroups', 'prevo', 'evoLevel', 'otherFormes',
       'formeOrder', 'canGigantamax', 'baseSpecies', 'forme', 'requiredItem',
       'changesFrom', 'evoCondition', 'evoType', 'gender', 'gen', 'evoItem',
       'evoRegion', 'canHatch', 'evoMove', 'tags', 'baseForme',
       'cosmeticFormes', 'maxHP', 'requiredAbility', 'battleOnly',
       'requiredMove', 'requiredItems', 'cannotDynamax', 'forceTeraType'],
      dtype='object')

In [5]:
pokedex_df.drop(['genderRatio', 'heightm', 'weightkg',
       'color', 'evoLevel', 'otherFormes',
       'formeOrder', 'canGigantamax', 'baseSpecies', 'requiredItem',
       'changesFrom', 'evoCondition', 'evoType', 'gender','evoItem',
       'evoRegion', 'canHatch', 'evoMove', 'tags', 'baseForme',
       'cosmeticFormes', 'maxHP', 'requiredAbility', 'battleOnly',
       'requiredMove', 'requiredItems', 'cannotDynamax', 'forceTeraType', 'gen'], axis = 1, inplace=True)

In [6]:
pokedex_df.head(10)

,num,name,types,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,abilities,evos,eggGroups,prevo,forme
0,1,Bulbasaur,"[Grass, Poison]",45,49,49,65,65,45,"[Overgrow, Chlorophyll]",[Ivysaur],"[Monster, Grass]",NaN,NaN
1,2,Ivysaur,"[Grass, Poison]",60,62,63,80,80,60,"[Overgrow, Chlorophyll]",[Venusaur],"[Monster, Grass]",Bulbasaur,NaN
2,3,Venusaur,"[Grass, Poison]",80,82,83,100,100,80,"[Overgrow, Chlorophyll]",NaN,"[Monster, Grass]",Ivysaur,NaN
3,3,Venusaur-Mega,"[Grass, Poison]",80,100,123,122,120,80,[Thick Fat],NaN,"[Monster, Grass]",NaN,Mega
4,3,Venusaur-Gmax,"[Grass, Poison]",80,82,83,100,100,80,"[Overgrow, Chlorophyll]",NaN,"[Monster, Grass]",NaN,Gmax
5,4,Charmander,[Fire],39,52,43,60,50,65,"[Blaze, Solar Power]",[Charmeleon],"[Monster, Dragon]",NaN,NaN
6,5,Charmeleon,[Fire],58,64,58,80,65,80,"[Blaze, Solar Power]",[Charizard],"[Monster, Dragon]",Charmander,NaN
7,6,Charizard,"[Fire, Flying]",78,84,78,109,85,100,"[Blaze, Solar Power]",NaN,"[Monster, Dragon]",Charmeleon,NaN
8,6,Charizard-Mega-X,"[Fire, Dragon]",78,130,111,130,85,100,[Tough Claws],NaN,"[Monster, Dragon]",NaN,Mega-X
9,6,Charizard-Mega-Y,"[Fire, Flying]",78,104,78,159,115,100,[Drought],NaN,"[Monster, Dragon]",NaN,Mega-Y

In [7]:
# Expand the list in the "Types" column into separate columns
types_df = pokedex_df['types'].apply(pd.Series)
# Rename the columns
types_df.columns = [f'type{i+1}' for i in range(types_df.shape[1])]
# Concatenate the expanded columns with the original DataFrame
pokedex_df = pd.concat([pokedex_df, types_df], axis=1)

In [8]:
# Expand the list in the "Types" column into separate columns
abilities_df = pokedex_df['abilities'].apply(pd.Series)
# Rename the columns
abilities_df.columns = [f'ability{i+1}' for i in range(abilities_df.shape[1])]
# Concatenate the expanded columns with the original DataFrame
pokedex_df = pd.concat([pokedex_df, abilities_df], axis=1)

In [9]:
pokedex_df.head(10)

,num,name,types,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,abilities,evos,eggGroups,prevo,forme,type1,type2,ability1,ability2,ability3,ability4
0,1,Bulbasaur,"[Grass, Poison]",45,49,49,65,65,45,"[Overgrow, Chlorophyll]",[Ivysaur],"[Monster, Grass]",NaN,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
1,2,Ivysaur,"[Grass, Poison]",60,62,63,80,80,60,"[Overgrow, Chlorophyll]",[Venusaur],"[Monster, Grass]",Bulbasaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
2,3,Venusaur,"[Grass, Poison]",80,82,83,100,100,80,"[Overgrow, Chlorophyll]",NaN,"[Monster, Grass]",Ivysaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
3,3,Venusaur-Mega,"[Grass, Poison]",80,100,123,122,120,80,[Thick Fat],NaN,"[Monster, Grass]",NaN,Mega,Grass,Poison,Thick Fat,NaN,NaN,NaN
4,3,Venusaur-Gmax,"[Grass, Poison]",80,82,83,100,100,80,"[Overgrow, Chlorophyll]",NaN,"[Monster, Grass]",NaN,Gmax,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
5,4,Charmander,[Fire],39,52,43,60,50,65,"[Blaze, Solar Power]",[Charmeleon],"[Monster, Dragon]",NaN,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN
6,5,Charmeleon,[Fire],58,64,58,80,65,80,"[Blaze, Solar Power]",[Charizard],"[Monster, Dragon]",Charmander,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN
7,6,Charizard,"[Fire, Flying]",78,84,78,109,85,100,"[Blaze, Solar Power]",NaN,"[Monster, Dragon]",Charmeleon,NaN,Fire,Flying,Blaze,Solar Power,NaN,NaN
8,6,Charizard-Mega-X,"[Fire, Dragon]",78,130,111,130,85,100,[Tough Claws],NaN,"[Monster, Dragon]",NaN,Mega-X,Fire,Dragon,Tough Claws,NaN,NaN,NaN
9,6,Charizard-Mega-Y,"[Fire, Flying]",78,104,78,159,115,100,[Drought],NaN,"[Monster, Dragon]",NaN,Mega-Y,Fire,Flying,Drought,NaN,NaN,NaN

In [10]:
pokedex_df.drop(['abilities','types'], axis = 1, inplace=True)

In [11]:
pokedex_df.head(10)

,num,name,HP,Attack,Defense,Sp.Atk,Sp.Def,Speed,evos,eggGroups,prevo,forme,type1,type2,ability1,ability2,ability3,ability4
0,1,Bulbasaur,45,49,49,65,65,45,[Ivysaur],"[Monster, Grass]",NaN,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
1,2,Ivysaur,60,62,63,80,80,60,[Venusaur],"[Monster, Grass]",Bulbasaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
2,3,Venusaur,80,82,83,100,100,80,NaN,"[Monster, Grass]",Ivysaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
3,3,Venusaur-Mega,80,100,123,122,120,80,NaN,"[Monster, Grass]",NaN,Mega,Grass,Poison,Thick Fat,NaN,NaN,NaN
4,3,Venusaur-Gmax,80,82,83,100,100,80,NaN,"[Monster, Grass]",NaN,Gmax,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN
5,4,Charmander,39,52,43,60,50,65,[Charmeleon],"[Monster, Dragon]",NaN,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN
6,5,Charmeleon,58,64,58,80,65,80,[Charizard],"[Monster, Dragon]",Charmander,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN
7,6,Charizard,78,84,78,109,85,100,NaN,"[Monster, Dragon]",Charmeleon,NaN,Fire,Flying,Blaze,Solar Power,NaN,NaN
8,6,Charizard-Mega-X,78,130,111,130,85,100,NaN,"[Monster, Dragon]",NaN,Mega-X,Fire,Dragon,Tough Claws,NaN,NaN,NaN
9,6,Charizard-Mega-Y,78,104,78,159,115,100,NaN,"[Monster, Dragon]",NaN,Mega-Y,Fire,Flying,Drought,NaN,NaN,NaN

In [12]:
pokedex_df.rename(columns={'HP':'hp', 'Attack': 'attack', 'Defense': 'defense', 'Sp.Atk':'sp. attack', 'Sp.Def':'sp. defense', 'Speed':'speed'}, inplace=True)

In [13]:
pokedex_df["total"] = pokedex_df[['hp', 'attack', 'defense', 'sp. attack', 'sp. defense', 'speed']].sum(axis=1)

In [14]:
pokedex_df.head(10)

,num,name,hp,attack,defense,sp. attack,sp. defense,speed,evos,eggGroups,prevo,forme,type1,type2,ability1,ability2,ability3,ability4,total
0,1,Bulbasaur,45,49,49,65,65,45,[Ivysaur],"[Monster, Grass]",NaN,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN,318
1,2,Ivysaur,60,62,63,80,80,60,[Venusaur],"[Monster, Grass]",Bulbasaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN,405
2,3,Venusaur,80,82,83,100,100,80,NaN,"[Monster, Grass]",Ivysaur,NaN,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN,525
3,3,Venusaur-Mega,80,100,123,122,120,80,NaN,"[Monster, Grass]",NaN,Mega,Grass,Poison,Thick Fat,NaN,NaN,NaN,625
4,3,Venusaur-Gmax,80,82,83,100,100,80,NaN,"[Monster, Grass]",NaN,Gmax,Grass,Poison,Overgrow,Chlorophyll,NaN,NaN,525
5,4,Charmander,39,52,43,60,50,65,[Charmeleon],"[Monster, Dragon]",NaN,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN,309
6,5,Charmeleon,58,64,58,80,65,80,[Charizard],"[Monster, Dragon]",Charmander,NaN,Fire,NaN,Blaze,Solar Power,NaN,NaN,405
7,6,Charizard,78,84,78,109,85,100,NaN,"[Monster, Dragon]",Charmeleon,NaN,Fire,Flying,Blaze,Solar Power,NaN,NaN,534
8,6,Charizard-Mega-X,78,130,111,130,85,100,NaN,"[Monster, Dragon]",NaN,Mega-X,Fire,Dragon,Tough Claws,NaN,NaN,NaN,634
9,6,Charizard-Mega-Y,78,104,78,159,115,100,NaN,"[Monster, Dragon]",NaN,Mega-Y,Fire,Flying,Drought,NaN,NaN,NaN,634

In [15]:
pokedex_df = pokedex_df[["num", "name", "type1", "type2", "total", "hp", "attack", "defense", "sp. attack", "sp. defense", "speed", "ability1", "ability2", "ability3", "ability4", "evos", "prevo", "forme"]]

In [16]:
pokedex_df.to_json("battle_pokedex_data2.json",orient='records')

In [17]:
pokedex_df["restricted"] = pokedex_df['name'].isin(["Mewtwo", "Mewtwo-Mega-X", "Mewtwo-Mega-Y", "Ho-oh", "Lugia", "Groudon", "Groudon-Primal", "Kyogre", "Kyogre-Primal", "Rayquaza", "Rayquaza-Mega", "Dialga", "Dialga-Origin", "Palkia", "Palkia-Origin", "Giratina", "Giratina-Origin", "Reshiram", "Zekrom", "Kyurem", "Kyurem White", "Kyurem Black", "Xerneas", "Xerneas-Neutral", "Yveltal", "Zygarde", "Zygarde-Complete", "Cosmog", "Cosmoem", "Solgaleo", "Lunala", "Necrozma", "Necrozma-Dusk-Mane", "Necrozma-Dawn-Wings", "Necrozma-Ultra", "Zacian", "Zacian-Crowned", "Zamazenta", "Zamazenta-Crowned", "Eternatus", "Eternatus-Eternamax", "Miraidon", "Koraidon", "Terapagos", "Terapagos-Terastal", "Terapagos-Stellar"])

In [27]:
pokedex_df["mythical"] = pokedex_df["name"].isin(["Mew", "Celebi", "Deoxys", "Jirachi", "Darkrai", "Keldeo", "Meloetta", "Volcanion", "Arceus", "Arceus-Water", "Arceus-Fire", "Arceus-Grass", "Arceus-Electric", "Arceus-Rock", "Arceus-Ground", "Arceus-Ice", "Arceus-Dragon", "Arceus-Fairy", "Arceus-Steel", "Arceus-Dark", "Arceus-Bug", "Arceus-Ghost", "Arceus-Poison", "Arceus-Fighting", "Arceus-Psychic", "Arceus-Flying", "Magearna", "Zarude", "Zarude-Dada", "Pecharunt"])

In [28]:
pokedex_df.head(10)

,num,name,type1,type2,total,hp,attack,defense,sp. attack,sp. defense,speed,ability1,ability2,ability3,ability4,evos,prevo,forme,restricted,mythical
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,Overgrow,Chlorophyll,NaN,NaN,[Ivysaur],NaN,NaN,False,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,Overgrow,Chlorophyll,NaN,NaN,[Venusaur],Bulbasaur,NaN,False,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Overgrow,Chlorophyll,NaN,NaN,NaN,Ivysaur,NaN,False,False
3,3,Venusaur-Mega,Grass,Poison,625,80,100,123,122,120,80,Thick Fat,NaN,NaN,NaN,NaN,NaN,Mega,False,False
4,3,Venusaur-Gmax,Grass,Poison,525,80,82,83,100,100,80,Overgrow,Chlorophyll,NaN,NaN,NaN,NaN,Gmax,False,False
5,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,Blaze,Solar Power,NaN,NaN,[Charmeleon],NaN,NaN,False,False
6,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,Blaze,Solar Power,NaN,NaN,[Charizard],Charmander,NaN,False,False
7,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,Blaze,Solar Power,NaN,NaN,NaN,Charmeleon,NaN,False,False
8,6,Charizard-Mega-X,Fire,Dragon,634,78,130,111,130,85,100,Tough Claws,NaN,NaN,NaN,NaN,NaN,Mega-X,False,False
9,6,Charizard-Mega-Y,Fire,Flying,634,78,104,78,159,115,100,Drought,NaN,NaN,NaN,NaN,NaN,Mega-Y,False,False

In [20]:
pokedex_df.to_csv("battle_pokedex_data.csv")

In [29]:
connection_string = 'postgresql://postgres:postgres@localhost:5433/postgres'

In [30]:
engine = create_engine(connection_string)

In [31]:
pokedex_df.to_sql('battle_pokedex', con=engine, if_exists='replace', index=False, schema='pokemon')

In [24]:
pokedex_df.head(10)

,num,name,type1,type2,total,hp,attack,defense,sp. attack,sp. defense,speed,ability1,ability2,ability3,ability4,evos,prevo,forme,restricted,mythical
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,Overgrow,Chlorophyll,NaN,NaN,[Ivysaur],NaN,NaN,False,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,Overgrow,Chlorophyll,NaN,NaN,[Venusaur],Bulbasaur,NaN,False,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,Overgrow,Chlorophyll,NaN,NaN,NaN,Ivysaur,NaN,False,False
3,3,Venusaur-Mega,Grass,Poison,625,80,100,123,122,120,80,Thick Fat,NaN,NaN,NaN,NaN,NaN,Mega,False,False
4,3,Venusaur-Gmax,Grass,Poison,525,80,82,83,100,100,80,Overgrow,Chlorophyll,NaN,NaN,NaN,NaN,Gmax,False,False
5,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,Blaze,Solar Power,NaN,NaN,[Charmeleon],NaN,NaN,False,False
6,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,Blaze,Solar Power,NaN,NaN,[Charizard],Charmander,NaN,False,False
7,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,Blaze,Solar Power,NaN,NaN,NaN,Charmeleon,NaN,False,False
8,6,Charizard-Mega-X,Fire,Dragon,634,78,130,111,130,85,100,Tough Claws,NaN,NaN,NaN,NaN,NaN,Mega-X,False,False
9,6,Charizard-Mega-Y,Fire,Flying,634,78,104,78,159,115,100,Drought,NaN,NaN,NaN,NaN,NaN,Mega-Y,False,False

In [25]:
import requests
from bs4 import BeautifulSoup

# URL of the webpage containing the data
url = "https://www.pikalytics.com/"

# Send a GET request to the webpage
response = requests.get(url)

# Parse the HTML content of the page
soup = BeautifulSoup(response.content, "html.parser")

# Find the <ul> element with class "list gen9vgc2024regf" and id "min_list"
ul_element = soup.find("ul", class_="list gen9vgc2024regf", id="min_list")
print(ul_element)
# Initialize an empty list to store the data
pokemon_list = []


# Print the scraped data
#print(pokemon_list)

None

In [26]:
# Initialize an empty list to store the data
pokemon_list = []

# Find all <a> elements with the specified class
a_elements = ul_element.find_all("a", class_="ss_entry pokedex_entry")

# Iterate over each <a> element
for a_element in a_elements:
    # Extract PokÃ©mon name
    pokemon_name = a_element.find("span", class_="pokemon-name").get_text(strip=True)
    
    # Extract PokÃ©mon percentage
    pokemon_percentage = a_element.find("span", class_="float-right margin-right-20").get_text(strip=True)
    
    # Append the extracted data to the list
    pokemon_list.append((pokemon_name, pokemon_percentage))

# Print the scraped data
print(pokemon_list)

AttributeError: 'NoneType' object has no attribute 'find_all'

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup
import time
from selenium.webdriver.common.by import By

In [ ]:
# Initialize the Selenium WebDriver
driver = webdriver.Chrome(executable_path="chromedriver.exe")  # Or specify the path to your WebDriver executable

# Load the webpage
driver.get("https://pikalytics.com")  # Replace with the URL of the webpage

# Find the specific element you want to scroll through
scrollable_element = driver.find_element(By.ID, "pokedex_wrapper")  # Replace "pokedex_wrapper" with the actual ID of the element

driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
time.sleep(30)
# Once all content is loaded, get the page source
page_source = driver.page_source

# Close the WebDriver
driver.quit()

# Parse the page source using BeautifulSoup
soup = BeautifulSoup(page_source, 'html.parser')

# Now you can extract the desired information from the soup object as needed

In [ ]:
print(page_source)

In [ ]:
ul_element = soup.find("ul", class_="list gen9vgc2024regf", id="min_list")

In [ ]:
#print(ul_element)

In [ ]:
moves_wrapper = ul_element.find_all("div", class_ = "pokedex-move-entry-new")
for move_element in moves_wrapper:
    # Extract PokÃ©mon name
    pokemon_name = move_element.find("span", class_="pokemon-name").get_text(strip=True)

In [ ]:
pokemon_list = []
a_elements2 = ul_element.find_all("a", class_="pokedex_entry")

# Iterate over each <a> element
for a_element in a_elements2:
    # Extract PokÃ©mon name
    pokemon_name2 = a_element.find("span", class_="pokemon-name").get_text(strip=True)
    
    pokemon_data = a_element.find("span", class_="pokemon-search").get_text(strip=True)
    # Extract PokÃ©mon percentage
    pokemon_percentage2 = a_element.find("span", class_="float-right margin-right-20").get_text(strip=True)
    print(pokemon_name2, pokemon_percentage2, pokemon_data)
    
    # Append the extracted data to the list
    pokemon_list.append((pokemon_name2, pokemon_percentage2, pokemon_data))

In [ ]:
#print(pokemon_list)

In [ ]:
pikalytics_df = pd.DataFrame(pokemon_list)

In [ ]:
pikalytics_df.head(10)

In [ ]:
pikalytics_df.to_csv("pikalytics_dataframe.csv")

In [ ]:
# Read the provided text
with open("gen9vgc2024regf-1760-moves.txt", "r") as file:
    text = file.read()

print(text)

In [ ]:
import re

# Remove all '+' characters
text = re.sub(r'\+', '', text)

# Remove all '-' characters
text = re.sub(r'-', '', text)

# Remove all '|' characters
text = re.sub(r'\|', '', text)

In [ ]:
print(text)

In [ ]:
text = re.sub(r'Abilities','Abilities:', text)

In [ ]:
print(text)

In [ ]:
text = re.sub(r'Items', 'Items:', text)
text = re.sub(r'Spreads', 'Spreads:', text)
text = re.sub(r'Moves', 'Moves:', text)
text = re.sub(r'Teammates', 'Teammates:', text)

In [ ]:
print(text)

In [ ]:
text = re.sub(r'Raw count:.*','', text)
text = re.sub(r'Avg\. weight:.*', '', text)
text = re.sub(r'Viability Ceiling:.*', '', text)

In [ ]:
print(text)

In [ ]:
text = re.sub(r'([a-zA-Z 2\-]+)\s+(Abilities)', r'\1\n\2', text)

In [ ]:
print(text)

In [ ]:
text2 = re.sub(r'(?<! )|(?! )', '', text)

In [ ]:
print(text2)

In [ ]:
text2 = re.sub(r'(?<!\w|\d)  ', '', text2)

In [ ]:
print(text2)

In [ ]:
text2 = re.sub(r'(?<=\w|\d)  ', ' ', text2)

In [ ]:
print(text2)

In [ ]:
text_array = text2.split('Checks and Counters')

In [ ]:
print(text_array)

In [ ]:
new_text_array = [string.replace('\n', ' ').strip() for string in text_array]

In [ ]:
print(new_text_array)

In [ ]:
string_extraction_pattern = re.compile(r'([a-zA-Z 2\%]+)\s+(Abilities:.*?)(Items:.*?)(Spreads:.*?)(Moves:.*?)(Teammates:.*)')

In [ ]:
test_string_extraction = [string_extraction_pattern.findall(elem) for elem in new_text_array]

In [ ]:
print(test_string_extraction)

In [ ]:
flattened_list = [[elem.strip() for elem in tup] for intermediary in test_string_extraction for tup in intermediary]

In [ ]:
print(flattened_list)

In [ ]:
bs_list = [[re.sub(r'% ', '%, ', elem) for elem in intermediary] for intermediary in flattened_list  ]

In [ ]:
print(bs_list)

In [ ]:
bs_list2 = [['Name: ' + elem if idx == 0 else elem for idx, elem in enumerate(sublist)] for sublist in bs_list]
print(bs_list2)

In [ ]:
bs_list3 = [[re.sub(r'\s+(\d)', r': \1', elem) for elem in sublist] for sublist in bs_list2]

In [ ]:
print(bs_list3)

In [ ]:
parsed_data = [{
    'Name': next(re.sub(r'([a-z])([A-Z])', r'\1 \2',item.split(': ', 1)[1].strip()) for item in entry if item.startswith('Name')),
    'Abilities': {ability.split(': ')[0].strip(): ability.split(': ')[1].strip() for item in entry if item.startswith('Abilities') for ability in item.split(': ', 1)[1].split(', ')},
    'Items': {item.split(': ')[0].strip(): item.split(': ')[1].strip() for item in next(item.split(': ', 1)[1] for item in entry if item.startswith('Items')).split(', ')},
    'Spreads': {spread.split(': ')[0].strip(): spread.split(': ')[1].strip() for spread in next(item.split(': ', 1)[1] for item in entry if item.startswith('Spreads')).split(', ')},
    'Moves': {move.split(': ')[0].strip(): move.split(': ')[1].strip() for move in next(item.split(': ', 1)[1] for item in entry if item.startswith('Moves')).split(', ')},
    'Teammates': {re.sub(r'([a-z])([A-Z])', r'\1 \2',teammate.split(': ')[0].strip()): teammate.split(': ')[1].strip() for teammate in next(item.split(': ', 1)[1] for item in entry if item.startswith('Teammates')).split(', ')}
} for entry in bs_list3]

print(parsed_data)

In [ ]:
pikalytics_df = pd.DataFrame(parsed_data)

In [ ]:
pikalytics_df.head(10)

In [ ]:
def limit_dict(d, max_items=8):
    return dict(list(d.items())[:max_items])

In [ ]:
pikalytics_df['Abilities'] = pikalytics_df['Abilities'].apply(lambda x: limit_dict(x))
pikalytics_df['Items'] = pikalytics_df['Items'].apply(lambda x: limit_dict(x))
pikalytics_df['Spreads'] = pikalytics_df['Spreads'].apply(lambda x: limit_dict(x))
pikalytics_df['Moves'] = pikalytics_df['Moves'].apply(lambda x: limit_dict(x))
pikalytics_df['Teammates'] = pikalytics_df['Teammates'].apply(lambda x: limit_dict(x))

In [ ]:
def split_dicts(dictionary,category):
    abilities_flat = {}
    for i, (ability, percentage) in enumerate(dictionary.items(), start=1):
        abilities_flat[f'{category}{i}'] = ability
        abilities_flat[f'Percentage_{category}{i}'] = percentage
    return abilities_flat

In [ ]:
# Apply the function to the Abilities column
abilities_expanded = pikalytics_df['Abilities'].apply(lambda x: split_dicts(x,'Ability'))
items_expanded = pikalytics_df['Items'].apply(lambda x: split_dicts(x,'Item'))
spreads_expanded = pikalytics_df['Spreads'].apply(lambda x: split_dicts(x,'Spread'))
moves_expanded = pikalytics_df['Moves'].apply(lambda x: split_dicts(x,'Move'))
teammates_expanded = pikalytics_df['Teammates'].apply(lambda x: split_dicts(x,'Teammate'))

In [ ]:
# Create a DataFrame from the expanded abilities
abilities_df = pd.DataFrame(abilities_expanded.tolist())
items_df = pd.DataFrame(items_expanded.tolist())
spreads_df = pd.DataFrame(spreads_expanded.tolist())
moves_df = pd.DataFrame(moves_expanded.tolist())
teammates_df = pd.DataFrame(teammates_expanded.tolist())

In [ ]:
items_df.head(5)

In [ ]:
# Merge the expanded abilities back into the original DataFrame
pikalytics_df = pikalytics_df.drop(columns=['Abilities', 'Items', 'Spreads', 'Moves', 'Teammates']).join(abilities_df)\
.join(items_df)\
.join(spreads_df)\
.join(moves_df)\
.join(teammates_df)

In [ ]:
pikalytics_df.head(10)

In [ ]:
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:postgres@localhost:5433/postgres')
pikalytics_df.to_sql('pikalytics_pokemon_data_dive', engine, schema='pokemon')

In [ ]:
# Read the provided text
with open("gen9vgc2024regf-1760.txt", "r") as file:
    gen9_regf = file.read()

print(gen9_regf)

In [ ]:

# Remove all '+' characters
gen9_regf = re.sub(r'\+', '', gen9_regf)

# Remove all '-' characters
gen9_regf = re.sub(r'-', '', gen9_regf)

# Remove all '|' characters
gen9_regf = re.sub(r'\|', '', gen9_regf)

In [ ]:
print(gen9_regf)

In [ ]:


# Apply the function to each line
gen9_regf_lines = gen9_regf.splitlines()
gen9_regf_processed_lines = [re.sub(r'(.*?%)\s.*', r'\1', elem) for elem in gen9_regf_lines]
gen9_regf_processed = '\n'.join(gen9_regf_processed_lines)

In [ ]:
print(gen9_regf_processed)

In [ ]:
tab_sep_gen9 = re.sub(r'\s*Total battles: 698352\s+Avg. weight/team: 0.004\s+', '', gen9_regf_processed)

In [ ]:
print(tab_sep_gen9)

In [ ]:
tab_formatted_gen9 = re.sub(r'\s*(Rank)\s*(Pokemon)\s*(Usage %)',r'\1\t\2\t\3',tab_sep_gen9)

In [ ]:
tab_formatted_gen9_list = tab_formatted_gen9.splitlines()
name_spaces_added = [re.sub(r'([a-z])([A-Z])', r'\1 \2', elem) for elem in tab_formatted_gen9_list]
tab_formatted_data = [re.sub(r'\s*(\d+)\s*([a-zA-Z ]+)\s*([\d+\.\d+%]+)',r'\1\t\2\t\3',elem) for elem in name_spaces_added]

In [ ]:
tab_sep_poke_pika_data = '\n'.join(tab_formatted_data)

In [ ]:
print(tab_sep_poke_pika_data)

In [ ]:
from io import StringIO
pikalytics_pokemon_usage_df = pd.read_csv(StringIO(tab_sep_poke_pika_data), delimiter='\t')

In [ ]:
pikalytics_pokemon_usage_df.head(10)

In [ ]:
pikalytics_pokemon_usage_df.to_sql('pikalytics_pokemon_usage', engine, schema='pokemon')

In [ ]:
# Convert to a list of dictionaries
dict_list = [
    {
        pair[0].strip(): {
            ' '.join(inner_pair[:-1]).strip(): inner_pair[-1].strip()
            for inner_pair in [item.split() for item in pair[1:]]
        } if '%' in ' '.join(pair) else pair[1].strip() 
        for pair in [elem.split(':', 1) for elem in sublist]
    } 
    for sublist in bs_list2
]

In [ ]:
<div class="table-team-wrapper"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/zamazenta-crowned.png" title="Zamazenta Crowned" alt="Zamazenta Crowned" width="64px"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/rillaboom.png" title="Rillaboom" alt="Rillaboom" width="64px"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/ogerpon-hearthflame.png" title="Ogerpon Hearthflame" alt="Ogerpon Hearthflame" width="64px"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/chien-pao.png" title="Chien Pao" alt="Chien Pao" width="64px"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/pelipper.png" title="Pelipper" alt="Pelipper" width="64px"><img src="https://victoryroadvgc.com/wp-content/uploads/sprites/gen9/flutter-mane.png" title="Flutter Mane" alt="Flutter Mane" width="64px"></div>